### ISSUE TITLE
Updating state took too long

### ISSUE THREAD

**Issue by Ayuus** [vincentwolsink/home_assistant_enphase_envoy_installer#111]
**Describe the bug**

Updating state for sensor.inverter_dc_current (<class 'custom_components.enphase_envoy.sensor.EnvoyInverterEntity'>) took 0.925 seconds.

**Account type**
- [ ] Installer

**Envoy**
- [ ] Metered without CTs

- FW version: D7.6.175
- Amount of micro inverters connected: 17

**Home Assistant**
- Version: 2024.3

**Additional context**
```
Relevant snippet of Home Assistant error log. 
```
Logger: homeassistant.helpers.entity
Bron: helpers/entity.py:1155
First occurred: 09:26:35 (1 gebeurtenissen)
Laatst gelogd: 09:26:35

Updating state for sensor.inverter_122011007219_dc_current (<class 'custom_components.enphase_envoy.sensor.EnvoyInverterEntity'>) took 0.925 seconds. Please create a bug report at https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/issues

**Comment by vincentwolsink** [comment]
Thanks for the report. Since all sensor updates happen async from an internal cache this should not happen. Maybe your HA instance/machine hosting it was a bit slow/occupied at that moment. Otherwise I would not know what causes this.

Assuming this is a glitch for now. Let me know if it happens regularly. Thanks.
